import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className="mx-auto flex max-h-screen w-[90%] md:w-[70%]">
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
